site_name: gdufs Wiki
site_author: name-longming
# Repository
repo_name: gdufswiki/gdufswiki
repo_url: https://github.com/gdufswiki/gdufswiki
edit_uri: docs

nav:
  - 简介:
      wiki简介 : index.md
  - 实验室介绍:
      网络空间安全实验室: laboratory/index.md
      计算语言学实验室: laboratory/index1.md
      ACM实验室: laboratory/ACM.md
  - 社团介绍:
      自律会: association/zlh.md
  - 关于学习:
      英语学习建议: study/index1.md
  - 关于标准:
      奖学金绩点综测: rules/index1.md
theme:
  name: null
  custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/library

  features:
    - navigation.tabs
    - navigation.top

  palette:
    
    # Light mode
    - blue: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
